config/routes.rb
Rails.application.routes.draw do
  resources :awards
  resources :reports
  resources :sub_tags
  resources :tags
  resources :reviews
  resources :rights_holders
  resources :creators
  resources :stored_products
  devise_for :users
  mount ShopifyApp::Engine, at: '/'

  root :to => 'products#index'
  get 'products' => 'products#index'
  post 'products' => 'products#create'

  # get '/auth/failure', to: redirect('/auth/shopify')

  namespace :api, :defaults => {:format => 'json'} do
    devise_for :users
    namespace :v1 do
      resources :products
      post 'generate_report' => 'reports#generate_report'
      post 'product_published' => 'products#product_published'
      post 'customer_created' => 'customers#create'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :stored_product
end

app/models/creator.rb
class Creator < ApplicationRecord
  belongs_to :stored_product
end

app/models/product.rb
class	Product
	def self.createShopifyProduct(product_data)
		@product = StoredProduct.new
		@product.assign_attributes(title: product_data['product']['title'], body_html: product_data['product']['body_html'])
		
	end

end

app/models/report.rb
class Report < ApplicationRecord
	has_attached_file :pdf
	validates_attachment :pdf, content_type: { content_type: "application/pdf" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stored_product
end

app/models/rights_holder.rb
class RightsHolder < ApplicationRecord
  belongs_to :stored_product
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  # include ShopifyApp::Shop
  include ShopifyApp::SessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/models/stored_product.rb
class StoredProduct < ActiveRecord::Base
	has_many :creators, dependent: :destroy
	has_many :rights_holders, dependent: :destroy
	has_many :reviews, dependent: :destroy
	has_many :tags, dependent: :destroy
	has_many :sub_tags, through: :tags
	has_many :awards, dependent: :destroy

	has_attached_file :featured_image,
	  styles: {
	        thumbnail: '100x100^',
	        header: '500x500^'
	      },
	      # convert_options: {
	      #   thumbnail: " -gravity center -crop '100x100+0+0'",
	      #   header: " -gravity center -crop '500x500+0+0'"
	      # },
	  default_url: "book.jpg"
	  validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/
	has_attached_file :vendor_logo,
	  styles: {
	        thumbnail: '100x100^',
	        header: '500x500^'
	      },
	      # convert_options: {
	      #   thumbnail: " -gravity center -crop '100x100+0+0'",
	      #   header: " -gravity center -crop '500x500+0+0'"
	      # },
	  default_url: "vendor.jpg"
	  validates_attachment_content_type :vendor_logo, content_type: /\Aimage\/.*\Z/  
end

app/models/sub_tag.rb
class SubTag < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :stored_product
  has_many :sub_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_token_authenticatable       
end

app/controllers/x_creators_controller.rb
class CreatorsController < ApplicationController
  before_action :set_creator, only: [:show, :edit, :update, :destroy]

  # GET /creators
  # GET /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1
  # GET /creators/1.json
  def show
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators
  # POST /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to @creator, notice: 'Creator was successfully created.' }
        format.json { render :show, status: :created, location: @creator }
      else
        format.html { render :new }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1
  # PATCH/PUT /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to @creator, notice: 'Creator was successfully updated.' }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1
  # DELETE /creators/1.json
  def destroy
    @creator.destroy
    respond_to do |format|
      format.html { redirect_to creators_url, notice: 'Creator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creator_params
      params.require(:creator).permit(:creator_type, :first_name, :last_name, :bio, :stored_product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verify_webhook(data, hmac_header)
		calculated_hmac = Base64.strict_encode64(OpenSSL::HMAC.digest('sha256', ENV['webhook_key'], data))
		ActiveSupport::SecurityUtils.secure_compare(calculated_hmac, hmac_header)
	end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sub_tags_helper.rb
module SubTagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/x_creators/_form.html.erb
<%= form_for(creator) do |f| %>
  <% if creator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creator.errors.count, "error") %> prohibited this creator from being saved:</h2>

      <ul>
      <% creator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :stored_product_id %>
    <%= f.text_field :stored_product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/x_creators/edit.html.erb
<h1>Editing Creator</h1>

<%= render 'form', creator: @creator %>

<%= link_to 'Show', @creator %> |
<%= link_to 'Back', creators_path %>

app/views/x_creators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creators</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Bio</th>
      <th>Stored product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creators.each do |creator| %>
      <tr>
        <td><%= creator.type %></td>
        <td><%= creator.first_name %></td>
        <td><%= creator.last_name %></td>
        <td><%= creator.bio %></td>
        <td><%= creator.stored_product %></td>
        <td><%= link_to 'Show', creator %></td>
        <td><%= link_to 'Edit', edit_creator_path(creator) %></td>
        <td><%= link_to 'Destroy', creator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creator', new_creator_path %>

app/views/x_creators/new.html.erb
<h1>New Creator</h1>

<%= render 'form', creator: @creator %>

<%= link_to 'Back', creators_path %>

app/views/x_creators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @creator.type %>
</p>

<p>
  <strong>First name:</strong>
  <%= @creator.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @creator.last_name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @creator.bio %>
</p>

<p>
  <strong>Stored product:</strong>
  <%= @creator.stored_product %>
</p>

<%= link_to 'Edit', edit_creator_path(@creator) %> |
<%= link_to 'Back', creators_path %>