config/routes.rb
Rails.application.routes.draw do
  resources :awards
  resources :reports
  resources :sub_tags
  resources :tags
  resources :reviews
  resources :rights_holders
  resources :creators
  resources :stored_products
  devise_for :users
  mount ShopifyApp::Engine, at: '/'

  root :to => 'products#index'
  get 'products' => 'products#index'
  post 'products' => 'products#create'

  # get '/auth/failure', to: redirect('/auth/shopify')

  namespace :api, :defaults => {:format => 'json'} do
    devise_for :users
    namespace :v1 do
      resources :products
      post 'generate_report' => 'reports#generate_report'
      post 'product_published' => 'products#product_published'
      post 'customer_created' => 'customers#create'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :stored_product
end

app/models/creator.rb
class Creator < ApplicationRecord
  belongs_to :stored_product
end

app/models/product.rb
class	Product
	def self.createShopifyProduct(product_data)
		@product = StoredProduct.new
		@product.assign_attributes(title: product_data['product']['title'], body_html: product_data['product']['body_html'])
		
	end

end

app/models/report.rb
class Report < ApplicationRecord
	has_attached_file :pdf
	validates_attachment :pdf, content_type: { content_type: "application/pdf" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stored_product
end

app/models/rights_holder.rb
class RightsHolder < ApplicationRecord
  belongs_to :stored_product
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  # include ShopifyApp::Shop
  include ShopifyApp::SessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/models/stored_product.rb
class StoredProduct < ActiveRecord::Base
	has_many :creators, dependent: :destroy
	has_many :rights_holders, dependent: :destroy
	has_many :reviews, dependent: :destroy
	has_many :tags, dependent: :destroy
	has_many :sub_tags, through: :tags
	has_many :awards, dependent: :destroy

	has_attached_file :featured_image,
	  styles: {
	        thumbnail: '100x100^',
	        header: '500x500^'
	      },
	      # convert_options: {
	      #   thumbnail: " -gravity center -crop '100x100+0+0'",
	      #   header: " -gravity center -crop '500x500+0+0'"
	      # },
	  default_url: "book.jpg"
	  validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/
	has_attached_file :vendor_logo,
	  styles: {
	        thumbnail: '100x100^',
	        header: '500x500^'
	      },
	      # convert_options: {
	      #   thumbnail: " -gravity center -crop '100x100+0+0'",
	      #   header: " -gravity center -crop '500x500+0+0'"
	      # },
	  default_url: "vendor.jpg"
	  validates_attachment_content_type :vendor_logo, content_type: /\Aimage\/.*\Z/  
end

app/models/sub_tag.rb
class SubTag < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :stored_product
  has_many :sub_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_token_authenticatable       
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :stored_product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verify_webhook(data, hmac_header)
		calculated_hmac = Base64.strict_encode64(OpenSSL::HMAC.digest('sha256', ENV['webhook_key'], data))
		ActiveSupport::SecurityUtils.secure_compare(calculated_hmac, hmac_header)
	end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sub_tags_helper.rb
module SubTagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/awards/_form.html.erb
<%= form_for(award) do |f| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :stored_product_id %>
    <%= f.text_field :stored_product_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing Award</h1>

<%= render 'form', award: @award %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stored product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.stored_product %></td>
        <td><%= link_to 'Show', award %></td>
        <td><%= link_to 'Edit', edit_award_path(award) %></td>
        <td><%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Award', new_award_path %>

app/views/awards/new.html.erb
<h1>New Award</h1>

<%= render 'form', award: @award %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Stored product:</strong>
  <%= @award.stored_product %>
</p>

<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>