config/routes.rb
Rails.application.routes.draw do
  resources :awards
  resources :reports
  resources :sub_tags
  resources :tags
  resources :reviews
  resources :rights_holders
  resources :creators
  resources :stored_products
  devise_for :users
  mount ShopifyApp::Engine, at: '/'

  root :to => 'products#index'
  get 'products' => 'products#index'
  post 'products' => 'products#create'

  # get '/auth/failure', to: redirect('/auth/shopify')

  namespace :api, :defaults => {:format => 'json'} do
    devise_for :users
    namespace :v1 do
      resources :products
      post 'generate_report' => 'reports#generate_report'
      post 'product_published' => 'products#product_published'
      post 'customer_created' => 'customers#create'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :stored_product
end

app/models/creator.rb
class Creator < ApplicationRecord
  belongs_to :stored_product
end

app/models/product.rb
class	Product
	def self.createShopifyProduct(product_data)
		@product = StoredProduct.new
		@product.assign_attributes(title: product_data['product']['title'], body_html: product_data['product']['body_html'])
		
	end

end

app/models/report.rb
class Report < ApplicationRecord
	has_attached_file :pdf
	validates_attachment :pdf, content_type: { content_type: "application/pdf" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stored_product
end

app/models/rights_holder.rb
class RightsHolder < ApplicationRecord
  belongs_to :stored_product
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  # include ShopifyApp::Shop
  include ShopifyApp::SessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end

app/models/stored_product.rb
class StoredProduct < ActiveRecord::Base
	has_many :creators, dependent: :destroy
	has_many :rights_holders, dependent: :destroy
	has_many :reviews, dependent: :destroy
	has_many :tags, dependent: :destroy
	has_many :sub_tags, through: :tags
	has_many :awards, dependent: :destroy

	has_attached_file :featured_image,
	  styles: {
	        thumbnail: '100x100^',
	        header: '500x500^'
	      },
	      # convert_options: {
	      #   thumbnail: " -gravity center -crop '100x100+0+0'",
	      #   header: " -gravity center -crop '500x500+0+0'"
	      # },
	  default_url: "book.jpg"
	  validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/
	has_attached_file :vendor_logo,
	  styles: {
	        thumbnail: '100x100^',
	        header: '500x500^'
	      },
	      # convert_options: {
	      #   thumbnail: " -gravity center -crop '100x100+0+0'",
	      #   header: " -gravity center -crop '500x500+0+0'"
	      # },
	  default_url: "vendor.jpg"
	  validates_attachment_content_type :vendor_logo, content_type: /\Aimage\/.*\Z/  
end

app/models/sub_tag.rb
class SubTag < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :stored_product
  has_many :sub_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_token_authenticatable       
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
  end
end

app/controllers/stored_products_controller.rb
class StoredProductsController < ShopifyApp::AuthenticatedController
  before_action :set_stored_product, only: [:show, :edit, :update, :destroy]

  # GET /stored_products
  # GET /stored_products.json
  def index
    @stored_products = StoredProduct.all
  end


  # GET /stored_products/1
  # GET /stored_products/1.json
  def show
  end

  # GET /stored_products/new
  def new
    @stored_product = StoredProduct.new
  end

  # GET /stored_products/1/edit
  def edit
  end

  # POST /stored_products
  # POST /stored_products.json
  def create
    @stored_product = StoredProduct.new(stored_product_params)

    respond_to do |format|
      if @stored_product.save
        format.html { redirect_to @stored_product, notice: 'Stored product was successfully created.' }
        format.json { render :show, status: :created, location: @stored_product }
      else
        format.html { render :new }
        format.json { render json: @stored_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stored_products/1
  # PATCH/PUT /stored_products/1.json
  def update
    respond_to do |format|
      if @stored_product.update(stored_product_params)
        format.html { redirect_to @stored_product, notice: 'Stored product was successfully updated.' }
        format.json { render :show, status: :ok, location: @stored_product }
      else
        format.html { render :edit }
        format.json { render json: @stored_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stored_products/1
  # DELETE /stored_products/1.json
  def destroy
    @stored_product.destroy
    respond_to do |format|
      format.html { redirect_to stored_products_url, notice: 'Stored product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stored_product
      @stored_product = StoredProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stored_product_params
      params.require(:stored_product).permit(:title, :body_html, :vendor, :product_type, :published, :featured_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verify_webhook(data, hmac_header)
		calculated_hmac = Base64.strict_encode64(OpenSSL::HMAC.digest('sha256', ENV['webhook_key'], data))
		ActiveSupport::SecurityUtils.secure_compare(calculated_hmac, hmac_header)
	end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stored_products_helper.rb
module StoredProductsHelper
end

app/helpers/sub_tags_helper.rb
module SubTagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/stored_products/_form.html.erb
<%= form_for(stored_product) do |f| %>
  <% if stored_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stored_product.errors.count, "error") %> prohibited this stored_product from being saved:</h2>

      <ul>
      <% stored_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body_html %>
    <%= f.text_field :body_html %>
  </div>

  <div class="field">
    <%= f.label :vendor %>
    <%= f.text_field :vendor %>
  </div>

  <div class="field">
    <%= f.label :product_type %>
    <%= f.text_field :product_type %>
  </div>

  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stored_products/edit.html.erb
<h1>Editing Stored Product</h1>

<%= render 'form', stored_product: @stored_product %>

<%= link_to 'Show', @stored_product %> |
<%= link_to 'Back', stored_products_path %>

app/views/stored_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stored Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body html</th>
      <th>Vendor</th>
      <th>Product type</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stored_products.each do |stored_product| %>
      <tr>
        <td><%= stored_product.title %></td>
        <td><%= stored_product.body_html %></td>
        <td><%= stored_product.vendor %></td>
        <td><%= stored_product.product_type %></td>
        <td><%= stored_product.published %></td>
        <td><%= link_to 'Show', stored_product %></td>
        <td><%= link_to 'Edit', edit_stored_product_path(stored_product) %></td>
        <td><%= link_to 'Destroy', stored_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stored Product', new_stored_product_path %>

app/views/stored_products/new.html.erb
<h1>New Stored Product</h1>

<%= render 'form', stored_product: @stored_product %>

<%= link_to 'Back', stored_products_path %>

app/views/stored_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @stored_product.title %>
</p>

<p>
  <strong>Body html:</strong>
  <%= @stored_product.body_html %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @stored_product.vendor %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @stored_product.product_type %>
</p>

<p>
  <strong>Published:</strong>
  <%= @stored_product.published %>
</p>

<%= link_to 'Edit', edit_stored_product_path(@stored_product) %> |
<%= link_to 'Back', stored_products_path %>